name: oquinena.com

on: [push]

jobs:
  Build_and_deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13

      - name: Generate site
        run: hugo

      - name: Deploy
        uses: Creepios/sftp-action@v1.0.4
        with:
          host: ${{ secrets.URL }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localPath: './public'
          remotePath: './'